# https://stackoverflow.com/questions/49586251/build-angular-project-using-aws-codebuild
version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: codepipeline-us-east-1-475045686144/angular-v9
        #BUILD_FOLDER: Artifacts
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp $CODEBUILD_SRC_DIR s3://${S3_BUCKET} --recursive #--acl public-read --cache-control "max-age=${CACHE_CONTROL}"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes